### ISSUE TITLE
Provide link when sharing

### ISSUE THREAD

**Issue by pgossman** [muhashi/geodle#1]
The copied content when clicking share doesnt contain a link to the website, so when sending scores between friends I have to dig around my history to find the site.

**Comment by muhashi** [comment]
The website is now hosted at [geodle.me](//geodle.me), and the copied content should resemble:

```
geodle.me 49 4/7
🟥🔽🟩🟩🔼🟥
🟥🔽🟩🟩🔼🟥
🟩🔽🟩🟩🔼🟥
🟩🟩🟩🟩🟩🟩
```

so the link can be remembered easily. Thank you for the suggestion!
