### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by LeopoldTal** [muhashi/geodle#3]
As of 2022-07-01T01:05:15.817Z, [https://geodle.me/](https://geodle.me/) 404s. [https://muhashi.github.io/geodle/](https://muhashi.github.io/geodle/) is served, but all the static resources it depends on (js, css) 404. Runs fine locally.

**Comment by muhashi** [comment]
Thanks for letting me know so fast! Should be back up now. Turns out the deployment script I use [removes custom domain settings](https://github.com/tschaub/gh-pages#deploying-to-github-pages-with-custom-domain) which broke the site.
